version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./drivers:/usr/share/logstash/drivers # mount folder chứa mysql-connector
    depends_on:
      - elasticsearch
    networks:
      - elk
    # === LIVEKIT SERVER ===
#  livekit:
#    image: livekit/livekit-server:latest
#    container_name: livekit
#    restart: unless-stopped
#    environment:
#      LIVEKIT_KEYS: "devkey: secret"
#      LIVEKIT_ANNOUNCE_URL: "http://192.168.67.109:7880"
#      LIVEKIT_LOG_LEVEL: info
#      LIVEKIT_WEBRTC_UDP_PORT: 5349
#      LIVEKIT_TURN_ENABLED: "true"
#    ports:
#      - '7880:7880' # HTTP / WebSocket
#      - '7881:7881' # gRPC (optional)
#      - '5349:5349/udp' # TURN / ICE UDP
#    networks:
#      - elk
networks:
  elk:
    driver: bridge
